*** Variables ***
# URLs de Checkout para diferentes carritos - PRODUCCIÓN
${CHECKOUT_PROD_SMALL}                 https://sv.siman.com/checkout/cart/add/?sku=8695234&qty=1&seller=1&sc=1&sku=8481414&qty=1&seller=1&sc=1
${CHECKOUT_PROD_SMALL_MK}              https://sv.siman.com/checkout/cart/add/?sku=10034338&qty=1&seller=Disprobe&sc=1
${CHECKOUT_PROD_BIG}                   https://sv.siman.com/checkout/cart/add/?sku=6810697&qty=1&seller=1&sc=1
${CHECKOUT_PROD_SPLIT_SIMAN}           https://sv.siman.com/checkout/cart/add/?sku=8523292&qty=1&seller=1&sc=1&sku=7849463&qty=1&seller=1&sc=1
${CHECKOUT_PROD_SPLIT_SIMAN_MK}        https://sv.siman.com/checkout/cart/add/?sku=10034338&qty=1&seller=Disprobe&sc=1&sku=8523292&qty=1&seller=1&sc=1


# URLs de Checkout para diferentes carritos - SANDBOX
${CHECKOUT_SANDBOX_SMALL}              https://simanqa.myvtex.com/checkout/cart/add/?sku=7469998&qty=1&seller=1&sc=1
${CHECKOUT_SANDBOX_SMALL_MK}           https://simanqa.myvtex.com/checkout/cart/add/?sku=7469998&qty=1&seller=1&sc=1
${CHECKOUT_SANDBOX_BIG}                https://simanqa.myvtex.com/checkout/cart/add/?sku=7469998&qty=1&seller=1&sc=1
${CHECKOUT_SANDBOX_SPLIT_SIMAN}        https://simanqa.myvtex.com/checkout/cart/add/?sku=7469998&qty=1&seller=1&sc=1
${CHECKOUT_SANDBOX_SPLIT_SIMAN_MK}     https://simanqa.myvtex.com/checkout/cart/add/?sku=7469998&qty=1&seller=1&sc=1